name: reusable action test for echo-ing a message

on:
  workflow_call:

runs:
  using: composite
  
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1

    # Runs a single command using the runner's shell
    - name: Run a one-line script
      shell: bash
      run: echo "Hello, reusable workflow is successfully called!"
